### PR TITLE
Add parsing for filament id

### PR DESCRIPTION
**Pull request by brisvag**
Hi all! I've been playing around with `pyem` over at [cs2star](https://github.com/brisvag/cs2star/) to get a quick-and-dirty cryosparc-to-relion conversion script. A colleague wanted access to the filament-id from cryosparc, and I thought the best way would be to contribute to the upstream parser in this repo.

This PR adds parsing of filament-id in cryosparc, for conversion to RELION star files. As far as I can tell it works, but let me know if I'm missing something or this isn't the right approach. Cheers!

### CODE REVIEW

**Comment by asarnow** [comment]
Hey, thanks for the PR, looks good. Do you think there will be more helical parameters that are more complex than the tube ID? I recall Relion has some additional filament-related data.

**Comment by brisvag** [comment]
There are several other parameters in cs files:
```python
 'filament/filament_uid',
 'filament/arc_length_A',
 'filament/straight_length_A',
 'filament/start_frac',
 'filament/end_frac',
 'filament/filament_pose',
 'filament/inter_box_dist_A',
 'filament/position_A',
 'filament/curvature',
 'filament/sinuosity'
```
I'm not familiar with filament handling in relion; do you have a pointer for where to look for the specs? I've guessed so far :P

**Comment by brisvag** [comment]
One thing that is missing when I try to use filament-picked particles is the orientation of these particles. I guess something similar to this is what is needed:
https://github.com/asarnow/pyem/blob/42af3ba0116ad31ce336ff6b9a36929871139a64/pyem/metadata.py#L340-L342

But it's hard for me at the moment to tell where this fits within the filament model in cryosparc. `filament/filament_pose` maybe, but how does that relate to `rlnAnglePsi`?

**Comment by asarnow** [comment]
OK, it seems like there's at least one more complicated piece of data to convert, so we'll keep the encapsulated function you wrote. I'm going to merge your PR. Then we can figure out how to convert the pose info correctly.

Do you have a Relion 3.1 filament .star file? I don't have an example handy.

**Comment by asarnow** [comment]
I didn't read through closely enough before. We don't need to copy the filament ID in `cryosparc_2_cs_filament_parameters()`, because once you add it to the dictionary in `parse_cryosparc_2_cs()` it gets converted automatically by `df = util.dataframe_from_records_mapped(cs, general)`. I wrote it like that to make adding these simple parameters extremely easy.

But we still need your encapsulated filament function for converting anything more complicated than a single value, such as the pose, and any parameters that are actually tuples (e.g. if `'filament/position_A'` a X,Y pair for each particle). Can you post the shapes of each of those filament-specific fields from the cs file? And do you have a Relion 3.1 filament .star we can use as a reference?

In the case of 2D classification you asked about, the `pose` is just a single number corresponding to the in-plane angle (`rlnAnglePsi`). The final conversion to degrees is at the end of `parse_cryosparc_2_cs()`. For 3D refinements, cryoSPARC uses Rodrigues vectors, which we store in the `rlnAngle*` fields until converting them to Euler angles (in degrees) on line 466. Filament pose is probably represented more-or-less the same way. When we compare the fields between the .cs file and a Relion 3.1 filament refinement .star we will be able to figure out what the correspondences are.

**Comment by brisvag** [comment]
Yes, I realized the function of `dataframe_from_records_mapped` later. I actually more or less solved the "pose" problem (it's a bit of a weird value compared to the "normal" pose) and moved around some code, but I won't go back to it until monday I think. If you can wait untik then to merge, I can push the changes and we can discuss those. I will also attach a sample file from cryosparc!

**Comment by brisvag** [comment]
Apologies for the delay - I just pushed the changes. While it seems to work on my end, I'm not entirely sure about the pose conversion. Cryosparc's `filament/filament_pose` appears to be using inverted handedness and a zero shifted by `pi/2` compared to `pose`, as far as I can tell.

**Comment by asarnow** [comment]
@brisvag I'm sorry I forgot about this stuff. I went ahead and merged your PR, I think the current state is good and we can add any further parameters we want from here. Have you verified that this pose conversion is correct (e.g. by 2D classification in Relion with `--skip-align`).

**Pull request merged**
