### PR TITLE
make scripts to proper package and define entry point

### PR DESCRIPTION
**Pull request by thorstenwagner**
Hi,

thanks for this great package!

I would like to propose a small refactoring of the scripts. Right now one have to create symbolic links into to bin folder, otherwise the scripts can't be called from everywhere. But this does not really goes together with the idea of a conda environment 

I would propose to make separate module `scripts` and put your scripts into this directory. Then I would define entry points in the `setup.py` for each script.

I did that for `csparc2star.py`, so you can see what changes are necessary. The name of the entry point is `pyem_csparc2star.py`. If you agree with that I can also do it for the remaining scripts. 

If you then install your package you can call your script with

`pyem_csparc2star.py`

And as soon you deactivate your conda environment, the commands are not available anymore which is great  :-)

Best,
Thorsten

### CODE REVIEW

**Comment by thorstenwagner** [comment]
Alright, I also added the remaining scripts to new scripts module :-)

Best,
Thorsten

**Comment by thorstenwagner** [comment]
I've also added a `entrypoint_prefix` variable to the `setup.py`.  So in case you don't like the `pyem_` prefix, just set it to ''

**Comment by asarnow** [comment]
@thorstenwagner @Anthchirp thank you - I just moved institutions and should have some time to merge this week.

**Comment by thorstenwagner** [comment]
@asarnow I resolved the conflicts in case you want to merge :-)

**Comment by asarnow** [comment]
I finally implemented this. Thank you for bringing it up and showing how to make the entry points!

I didn't add the scripts entries to setup.py, just to meta.yaml. Sounds like conda will overwrite the setup.py ones anyway.

**Pull request closed without merging**
